### ISSUE TITLE
Migrating website to new theme and re-building

### ISSUE THREAD

**Issue by jyoti-bhogal** [researchsoft/website#34]
Tasks:

- [x] https://github.com/researchsoft/website/issues/27
- [x] https://github.com/researchsoft/website/issues/30
- [ ] https://github.com/researchsoft/website/issues/32
- [x] #35
