### ISSUE TITLE
Configure 'Forums' section

### ISSUE THREAD

**Issue by jyoti-bhogal** [researchsoft/website#38]
Configure the following pages/sections:

- [ ] Funders forum
- [ ] Research software infrastructure forum
- [ ] International council of RSE associations
- [ ] Community leaders forum
