### ISSUE TITLE
Render Images, Logos, etc.

### ISSUE THREAD

**Issue by jyoti-bhogal** [researchsoft/website#71]
For each of the following pages, render images/logos, etc.:

- [ ] Home: People, Infrastructure, Policy
- [ ] About/About: Founding Members, Organisational Members, Sponsors, Partners, Past Sponsors
- [ ] About/Governance: Images and Text for ReSA Steering Committee, Chairs of ReSA Subcommittees (note, currently part of the text is in the About/People page)
- [ ] About/People: Images and text
- [ ] About/Membership: Organisational Members
- [ ] Forums/Community Leaders Forum
- [ ] Events: Cover images
- [ ] [Optional] Blog: For each blog, Syna theme does not have any image on Cover of the blog. However, Ananke theme requires image by default. Therefore, in Ananke theme, either change this default code or render the images (provided the blog has one or add some generic image)
